---
title: "Jon"
author: "Jonathan Dufault"
date: "11/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rpart)
library(pROC)
library(ggplot2)
library(readr)
library(randomForest)

jonEnv = new.env()

with(jonEnv,{
  train <- read_csv("train.csv")
  test <- read_csv("test.csv")
  
  train$train = 1
  test$train = 0
  
  augment = rbind(test,train)
  
  
  factorstring = c("SEX","EDUCATION","MARRIAGE","PAY_0","PAY_2","PAY_3","PAY_4","PAY_5","PAY_6","default.payment.next.month")
  train[,factorstring] = lapply(train[,factorstring],as.factor)
  test[,factorstring] = lapply(test[,factorstring],as.factor)
})
```



```{r}
  with(jonEnv,{
  p = ggplot(train,aes(x=SEX,  
                      y=EDUCATION, 
                      color=default.payment.next.month))
  
  p + geom_jitter(alpha=0.3) +  
    scale_color_manual(breaks = c('No Default','Default'),
                       values=c('darkgreen','red'))
  
})
```


```{r}
  with(jonEnv,{
  p = ggplot(train,aes(x=PAY_0,  
                      y=PAY_3, 
                      color=default.payment.next.month))
  
  p + geom_jitter(alpha=0.3) +  
    scale_color_manual(breaks = c('No Default','Default'),
                       values=c('darkgreen','red'))
  
})
```


```{r}
with(jonEnv,{
  p = ggplot(train,aes(x=MARRIAGE,  
                      y=SEX, 
                      color=default.payment.next.month))
  
  p + geom_jitter(alpha=0.3) +  
    scale_color_manual(breaks = c('No Default','Default'),
                       values=c('darkgreen','red'))
})
```


```{r}

with(jonEnv,{
  p = ggplot(train,aes(x=MARRIAGE,  
                      y=SEX, 
                      color=default.payment.next.month))
  
  p + geom_jitter(alpha=0.3) +  
    scale_color_manual(breaks = c('No Default','Default'),
                       values=c('darkgreen','red'))
})  
```

```{r}
  with(jonEnv,{
  model = rpart(default.payment.next.month ~ . , data=train,method="class")
  
  printcp(model)
  
  plotcp(model)
  
  plot(model, uniform=TRUE,
     main="Classification Tree for Defaults")
  text(model, use.n=TRUE, all=TRUE, cex=.8)
})
```



```{r}
with(jonEnv,{
  predictions = predict(model,newdata=test)
  
  plot(roc(test$default.payment.next.month,predictions))
})
```



